### ISSUE TITLE
Silent failure on missing key in list

### ISSUE THREAD

**Issue by dominicwhittle** [seven-phases-max/less-plugin-lists#10]
Loving this plugin ❤️
My only gripe so far is that if I look up a value by key and that key doesn't exist we get a silent failure, as follows:

```less
@palette:
  primary #0000E0,
  info #02d7e1,
  success #02e10c;

h1 {
  color: at(@palette, primary);
  background-color: at(@palette, infos); // <-- typo (should be 'info' not 'infos')
  border-color: at(@palette, success);
}
```

Results in:
```css
h1 {
  color: #0000E0;
  background-color: at(primary #0000E0, info #02d7e1, success #02e10c, infos); // 😱
  border-color: #02e10c;
}
```

I've forked and "fixed" here by throwing an error — https://github.com/dominicwhittle/less-plugin-lists/pull/1/files

Please take this as a suggestion, I'm not well versed in the code base nor the community around this plugin for this to be anything more than my personal suggestion.
