### ISSUE TITLE
function at can't build a right value

### ISSUE THREAD

**Issue by missyliu** [seven-phases-max/less-plugin-lists#2]
example url: [less-plugin-lists/docs/ref.examples/at.less](https://github.com/seven-phases-max/less-plugin-lists/blob/master/docs/ref.examples/at.less)
input:

``` less
@color:
    a #000,
    b #111,
    c #222;

#header {
    color: at(@color, a);
}
```

output:

``` css
#header {
    color: at(a "#000", b "#111", c "#222", a);
}
```

**Comment by seven-phases-max** [comment]
Sorry I can't test it right now (I'll try in a few days), but considering there's pretty similar [test](https://github.com/seven-phases-max/less-plugin-lists/blob/master/test/less/at.less) that passes fine, are you sure the plugin is actually enabled? I.e. what result do you get if comping the said [test](https://github.com/seven-phases-max/less-plugin-lists/blob/master/test/less/at.less)?

**Comment by seven-phases-max** [comment]
So I've tested this and it works as expected, resulting in:

``` css
#header {
  color: #000;
}
```

I guess this is why the issue is closed (w/o the plugin enabled, Less compiler will leave unknown function statements as-is assuming it some new CSS function, hence most likely the result you had).
